import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Social from "@/components/Social";

import {Providers} from "../providers";

export const metadata: Metadata = {
  title: 'Olin Library New Books',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" className='dark'>
      <body>
        <Providers>
          <Header />
          <Social />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
